TRUNCATE TABLE "Product" CASCADE;
INSERT INTO "Category" (id, name, slug, "isB2C", "isB2B") VALUES ('cl0xnlukipryuva1e', 'Frozen Foods', 'frozen-foods', true, false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Category" (id, name, slug, "isB2C", "isB2B") VALUES ('cr4taev4dbvp2sy9u', 'Cakes, Pastries & Desserts', 'cakes-pastries-desserts', true, false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Category" (id, name, slug, "isB2C", "isB2B") VALUES ('c0d605vwyffvis9ve', 'Gift Items & Hampers', 'gift-items-hampers', true, false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Category" (id, name, slug, "isB2C", "isB2B") VALUES ('ccy7w4j7uro59oq9b', 'Home Baker Essentials', 'home-baker-essentials', true, false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Category" (id, name, slug, "isB2C", "isB2B") VALUES ('cbwjskzt90brib5zg', 'Party & Decoration Items', 'party-decoration-items', true, false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Category" (id, name, slug, "isB2C", "isB2B") VALUES ('cunodsbes6fz9hdtg', 'Bakery, Sweets & Restaurant', 'bakery-sweets-restaurant', true, false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Category" (id, name, slug, "isB2C", "isB2B") VALUES ('cqwdfcs1eselp1e7a', 'Baking Tools & Equipment', 'baking-tools-equipment', true, false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Category" (id, name, slug, "isB2C", "isB2B") VALUES ('cx8vmwxiqpacyqisd', 'Confectionery & Home Goods', 'confectionery-home-goods', true, false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Category" (id, name, slug, "isB2C", "isB2B") VALUES ('czlahfd5m52zydlwc', 'Snacks & Chocolates', 'snacks-chocolates', true, false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Category" (id, name, slug, "isB2C", "isB2B") VALUES ('c95m1it5y1ik0flne', 'Beverages', 'beverages', true, false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pv4ww863d0x5nbnim', 'Mala''s Strawberry Jam', 'mala-s-strawberry-jam-klq7', 'Mala''s Strawberry Jam (200 g)', 50, 100, true, '200 g', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pv4ww863d0x5nbnim', 'cx8vmwxiqpacyqisd');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pijtj826zg', 'pv4ww863d0x5nbnim', 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pwsgk18aqb3bak8i2', 'Pintola Peanut Butter', 'pintola-peanut-butter-z2rr', 'Pintola Peanut Butter (350 g)', 170, 100, true, '350 g', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pwsgk18aqb3bak8i2', 'cx8vmwxiqpacyqisd');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pik4fvrnib', 'pwsgk18aqb3bak8i2', 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('p9u1yl6dg7ou6g87h', 'Hellmann''s Mayonnaise', 'hellmann-s-mayonnaise-ibwa', 'Hellmann''s Mayonnaise (250 g)', 90, 100, true, '250 g', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('p9u1yl6dg7ou6g87h', 'cx8vmwxiqpacyqisd');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pio3m5l4os', 'p9u1yl6dg7ou6g87h', 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pkm4c9hntv4awlkt3', 'Pente Vuna Apple Juice', 'pente-vuna-apple-juice-bzpc', 'Pente Vuna Apple Juice (1 L)', 120, 100, true, '1 L', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pkm4c9hntv4awlkt3', 'cx8vmwxiqpacyqisd');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pi6wyw836v', 'pkm4c9hntv4awlkt3', 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pawah85j0x7s2ob15', 'Amul Fresh Cream', 'amul-fresh-cream-gwau', 'Amul Fresh Cream (250 ml)', 72, 100, true, '250 ml', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pawah85j0x7s2ob15', 'cx8vmwxiqpacyqisd');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pi1kfx1azk', 'pawah85j0x7s2ob15', 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('piq8oxehnkdn8ubxb', 'Cadbury Celebrations', 'cadbury-celebrations-cb3o', 'Cadbury Celebrations (109.64 g)', 110, 100, true, '109.64 g', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('piq8oxehnkdn8ubxb', 'czlahfd5m52zydlwc');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pidkubuh57', 'piq8oxehnkdn8ubxb', 'https://images.unsplash.com/photo-1581798459219-318e76aecc7b?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pjotoeigz150o65fq', 'Bikaji Bikaneri Bhujia', 'bikaji-bikaneri-bhujia-kuxa', 'Bikaji Bikaneri Bhujia (200 g)', 60, 100, true, '200 g', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pjotoeigz150o65fq', 'czlahfd5m52zydlwc');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('piy5oejqa8', 'pjotoeigz150o65fq', 'https://images.unsplash.com/photo-1581798459219-318e76aecc7b?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('ph9n62e7ruk0fox9n', 'Amul Choco Minis', 'amul-choco-minis-hs81', 'Amul Choco Minis (250 g)', 130, 100, true, '250 g', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('ph9n62e7ruk0fox9n', 'czlahfd5m52zydlwc');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pi1o5pv87a', 'ph9n62e7ruk0fox9n', 'https://images.unsplash.com/photo-1581798459219-318e76aecc7b?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pev4pjmjk69w1w3yj', 'Pringles Sour Cream & Onion', 'pringles-sour-cream-onion-s05m', 'Pringles Sour Cream & Onion (40 g)', 55, 100, true, '40 g', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pev4pjmjk69w1w3yj', 'czlahfd5m52zydlwc');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pi9q5x1mmb', 'pev4pjmjk69w1w3yj', 'https://images.unsplash.com/photo-1581798459219-318e76aecc7b?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pe8unmrlbj7pz4y3b', 'Samyang Buldak Carbonara Noodles', 'samyang-buldak-carbonara-noodles-sdaz', 'Samyang Buldak Carbonara Noodles (130 g)', 150, 100, true, '130 g', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pe8unmrlbj7pz4y3b', 'czlahfd5m52zydlwc');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pi7kyokeze', 'pe8unmrlbj7pz4y3b', 'https://images.unsplash.com/photo-1581798459219-318e76aecc7b?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('poojhhxamcykjf6dd', 'Red Bull Energy Drink', 'red-bull-energy-drink-xpwr', 'Red Bull Energy Drink (250 ml)', 125, 100, true, '250 ml', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('poojhhxamcykjf6dd', 'c95m1it5y1ik0flne');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('piyj1qsy0a', 'poojhhxamcykjf6dd', 'https://images.unsplash.com/photo-1527960656366-ee2a999e3286?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pcf8am9d4yl8nai34', 'Monster Energy Drink', 'monster-energy-drink-uxyf', 'Monster Energy Drink (350 ml)', 125, 100, true, '350 ml', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pcf8am9d4yl8nai34', 'c95m1it5y1ik0flne');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pih5uvpik2', 'pcf8am9d4yl8nai34', 'https://images.unsplash.com/photo-1527960656366-ee2a999e3286?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('phjtqsv9l4l4dnc5z', 'Nescafé Iced Latte', 'nescaf-iced-latte-6yha', 'Nescafé Iced Latte (170 ml)', 50, 100, true, '170 ml', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('phjtqsv9l4l4dnc5z', 'c95m1it5y1ik0flne');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pi5buiq2vc', 'phjtqsv9l4l4dnc5z', 'https://images.unsplash.com/photo-1527960656366-ee2a999e3286?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('ps09rt54q7b7yjcbj', 'Pepsi', 'pepsi-2eku', 'Pepsi (750 ml)', 40, 100, true, '750 ml', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('ps09rt54q7b7yjcbj', 'c95m1it5y1ik0flne');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pi6b1t964z', 'ps09rt54q7b7yjcbj', 'https://images.unsplash.com/photo-1527960656366-ee2a999e3286?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pitfkuh1i5obohkbj', 'Mirinda', 'mirinda-psxc', 'Mirinda (750 ml)', 40, 100, true, '750 ml', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pitfkuh1i5obohkbj', 'c95m1it5y1ik0flne');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pisyj3kl18', 'pitfkuh1i5obohkbj', 'https://images.unsplash.com/photo-1527960656366-ee2a999e3286?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pyofyd7r6dnvaj7gs', 'McCain Smiles (Veg)', 'mccain-smiles-veg-bk36', 'McCain Smiles (Veg) (415 g)', 150, 100, true, '415 g', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pyofyd7r6dnvaj7gs', 'cl0xnlukipryuva1e');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pi1x5n0b69', 'pyofyd7r6dnvaj7gs', 'https://images.unsplash.com/photo-1560684352-8497838a2229?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('p3pik2ijr0r9td538', 'Amul French Fries (Veg)', 'amul-french-fries-veg-dmwv', 'Amul French Fries (Veg) (200 g)', 40, 100, true, '200 g', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('p3pik2ijr0r9td538', 'cl0xnlukipryuva1e');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pix0i99lsi', 'p3pik2ijr0r9td538', 'https://images.unsplash.com/photo-1560684352-8497838a2229?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('ph0xrn30gjjmibqsj', 'Delicious Chicken Nuggets', 'delicious-chicken-nuggets-wbtk', 'Delicious Chicken Nuggets (250 g)', 160, 100, true, '250 g', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('ph0xrn30gjjmibqsj', 'cl0xnlukipryuva1e');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pidt15ftrb', 'ph0xrn30gjjmibqsj', 'https://images.unsplash.com/photo-1560684352-8497838a2229?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pv46jb88nzt0v0kz3', 'Meatzza Chicken Sausages', 'meatzza-chicken-sausages-75ha', 'Meatzza Chicken Sausages (250 g)', 165, 100, true, '250 g', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pv46jb88nzt0v0kz3', 'cl0xnlukipryuva1e');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pinxuypo81', 'pv46jb88nzt0v0kz3', 'https://images.unsplash.com/photo-1560684352-8497838a2229?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pb2va4vfaz4v3bo7j', 'Amul Malai Paneer', 'amul-malai-paneer-lfjw', 'Amul Malai Paneer (200 g)', 99, 100, true, '200 g', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pb2va4vfaz4v3bo7j', 'cl0xnlukipryuva1e');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pik1352twp', 'pb2va4vfaz4v3bo7j', 'https://images.unsplash.com/photo-1560684352-8497838a2229?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('plyafogcpy2v6yh2a', 'Chocolate Cake', 'chocolate-cake-dnwe', 'Chocolate Cake (1 Pound)', 500, 100, true, '1 Pound', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('plyafogcpy2v6yh2a', 'cr4taev4dbvp2sy9u');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pii0c62w20', 'plyafogcpy2v6yh2a', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('phitxze4sbg6s8yua', 'Vanilla Cake', 'vanilla-cake-lhqz', 'Vanilla Cake (1 Pound)', 400, 100, true, '1 Pound', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('phitxze4sbg6s8yua', 'cr4taev4dbvp2sy9u');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pi5q1mzir0', 'phitxze4sbg6s8yua', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pulct8bv4rz5qnq9l', 'Black Forest Pastry', 'black-forest-pastry-arjc', 'Black Forest Pastry (Per Piece)', 80, 100, true, 'Per Piece', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pulct8bv4rz5qnq9l', 'cr4taev4dbvp2sy9u');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('picx74na79', 'pulct8bv4rz5qnq9l', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pl2jbxraktkajrzrc', 'Blueberry Panda Pastry', 'blueberry-panda-pastry-482c', 'Blueberry Panda Pastry (Per Piece)', 90, 100, true, 'Per Piece', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pl2jbxraktkajrzrc', 'cr4taev4dbvp2sy9u');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pino5ceadc', 'pl2jbxraktkajrzrc', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pl6zookimplpph3u8', 'Glass Cake (Chocolate / Strawberry)', 'glass-cake-chocolate-strawberry-rr8q', 'Glass Cake (Chocolate / Strawberry) (Per Piece)', 80, 100, true, 'Per Piece', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pl6zookimplpph3u8', 'cr4taev4dbvp2sy9u');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('piq8m63bif', 'pl6zookimplpph3u8', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pcw8xctlh01y9chxm', 'Lord Ganesha Water Fountain', 'lord-ganesha-water-fountain-4xod', 'Lord Ganesha Water Fountain (1 Pc)', 2500, 100, true, '1 Pc', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pcw8xctlh01y9chxm', 'c0d605vwyffvis9ve');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pieuxvs0i1', 'pcw8xctlh01y9chxm', 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pjngyvdrn1xrexnzz', 'Home Bird Showpiece', 'home-bird-showpiece-c448', 'Home Bird Showpiece (1 Pc)', 1200, 100, true, '1 Pc', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pjngyvdrn1xrexnzz', 'c0d605vwyffvis9ve');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('piw3nij02c', 'pjngyvdrn1xrexnzz', 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pqskkrzl33ghi4mem', 'Peacock Showpiece', 'peacock-showpiece-gqhj', 'Peacock Showpiece (1 Pc)', 1200, 100, true, '1 Pc', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pqskkrzl33ghi4mem', 'c0d605vwyffvis9ve');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('piv69oqz0m', 'pqskkrzl33ghi4mem', 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pmgmrtq0i37lucnie', 'Buddha Showpiece', 'buddha-showpiece-d4iz', 'Buddha Showpiece (1 Pc)', 500, 100, true, '1 Pc', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pmgmrtq0i37lucnie', 'c0d605vwyffvis9ve');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pifc56nvel', 'pmgmrtq0i37lucnie', 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('phjei6s821ucz9wb6', 'Umbrella Couple Showpiece', 'umbrella-couple-showpiece-6mms', 'Umbrella Couple Showpiece (1 Pc)', 950, 100, true, '1 Pc', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('phjei6s821ucz9wb6', 'c0d605vwyffvis9ve');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pikdjd7j7y', 'phjei6s821ucz9wb6', 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pf1j4vgu13avnruj4', 'Goodrich White Gold Whipping Cream', 'goodrich-white-gold-whipping-cream-gz6s', 'Goodrich White Gold Whipping Cream (1 L)', 180, 100, true, '1 L', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pf1j4vgu13avnruj4', 'ccy7w4j7uro59oq9b');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pibah0se36', 'pf1j4vgu13avnruj4', 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pp4zcxhif7mwg8vo8', 'Vanilla Essence', 'vanilla-essence-l9wh', 'Vanilla Essence (20 ml)', 30, 100, true, '20 ml', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pp4zcxhif7mwg8vo8', 'ccy7w4j7uro59oq9b');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pij9z7f1lj', 'pp4zcxhif7mwg8vo8', 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('plgzkidellxuylfbp', 'Liquid Food Colour', 'liquid-food-colour-6nb5', 'Liquid Food Colour (20 ml)', 30, 100, true, '20 ml', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('plgzkidellxuylfbp', 'ccy7w4j7uro59oq9b');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pi38k5slnv', 'plgzkidellxuylfbp', 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pgavfu8u3ax06sx1f', '1 Pound Corrugated Cake Box', '1-pound-corrugated-cake-box-kd33', '1 Pound Corrugated Cake Box (Per Piece)', 20, 100, true, 'Per Piece', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pgavfu8u3ax06sx1f', 'ccy7w4j7uro59oq9b');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('piauq3f97p', 'pgavfu8u3ax06sx1f', 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('p9rjr9qgacenypxf4', '1 Pound Corrugated Cake Base', '1-pound-corrugated-cake-base-1d0n', '1 Pound Corrugated Cake Base (Per Piece)', 10, 100, true, 'Per Piece', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('p9rjr9qgacenypxf4', 'ccy7w4j7uro59oq9b');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pi6u8y6n21', 'p9rjr9qgacenypxf4', 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pvj1rv5ywa7q8a665', 'Mix Colour Balloons (50 pcs)', 'mix-colour-balloons-50-pcs-gxu2', 'Mix Colour Balloons (50 pcs) (Per Pack)', 80, 100, true, 'Per Pack', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pvj1rv5ywa7q8a665', 'cbwjskzt90brib5zg');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pi5s3sw82p', 'pvj1rv5ywa7q8a665', 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('p2n5ixf5mwzng0fs7', '288 Shots Firecracker', '288-shots-firecracker-1a79', '288 Shots Firecracker (Per Piece)', 1200, 100, true, 'Per Piece', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('p2n5ixf5mwzng0fs7', 'cbwjskzt90brib5zg');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pibouiwdhj', 'p2n5ixf5mwzng0fs7', 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pj05f6fr5rns6t4je', 'Spiral Candles', 'spiral-candles-h8z2', 'Spiral Candles (Per Pack)', 50, 100, true, 'Per Pack', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pj05f6fr5rns6t4je', 'cbwjskzt90brib5zg');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pijncmwt8u', 'pj05f6fr5rns6t4je', 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('p90ynbxljpnndg8nl', 'LED Glasses', 'led-glasses-btay', 'LED Glasses (Per Piece)', 80, 100, true, 'Per Piece', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('p90ynbxljpnndg8nl', 'cbwjskzt90brib5zg');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pi6oa4zv1r', 'p90ynbxljpnndg8nl', 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pogyxcegbh5aos6xe', 'Pyro Gun', 'pyro-gun-j2uy', 'Pyro Gun (Per Piece)', 200, 100, true, 'Per Piece', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pogyxcegbh5aos6xe', 'cbwjskzt90brib5zg');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('piz7aio7u4', 'pogyxcegbh5aos6xe', 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pqgg1tv3ytp3s664w', 'Chicken Roll', 'chicken-roll-acjg', 'Chicken Roll (Per Piece)', 100, 100, true, 'Per Piece', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pqgg1tv3ytp3s664w', 'cunodsbes6fz9hdtg');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pidt58whja', 'pqgg1tv3ytp3s664w', 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('p1s9rd6l2xptbzfl1', 'Paneer Patties', 'paneer-patties-gm9n', 'Paneer Patties (Per Piece)', 30, 100, true, 'Per Piece', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('p1s9rd6l2xptbzfl1', 'cunodsbes6fz9hdtg');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pixhup8mlq', 'p1s9rd6l2xptbzfl1', 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('p3sc9ma3hh8ix2wjp', 'Rasmalai', 'rasmalai-bu37', 'Rasmalai (Per Piece)', 40, 100, true, 'Per Piece', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('p3sc9ma3hh8ix2wjp', 'cunodsbes6fz9hdtg');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pi3d09rul9', 'p3sc9ma3hh8ix2wjp', 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pjjh22wh7hk06jjpx', 'Khasta Kachori', 'khasta-kachori-f6bw', 'Khasta Kachori (250 g)', 50, 100, true, '250 g', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pjjh22wh7hk06jjpx', 'cunodsbes6fz9hdtg');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pi3denu9tx', 'pjjh22wh7hk06jjpx', 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pwypudl087cliwt5q', 'Bakery Bhujia', 'bakery-bhujia-f0b1', 'Bakery Bhujia (200 g)', 50, 100, true, '200 g', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pwypudl087cliwt5q', 'cunodsbes6fz9hdtg');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pibsd7mbsp', 'pwypudl087cliwt5q', 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('p5kqyee4a4hpt343o', 'Cake Icing Knife', 'cake-icing-knife-pwnj', 'Cake Icing Knife (Per Piece)', 220, 100, true, 'Per Piece', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('p5kqyee4a4hpt343o', 'cqwdfcs1eselp1e7a');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pi1g13w6ly', 'p5kqyee4a4hpt343o', 'https://images.unsplash.com/photo-1595908129746-57ca1a63dd4d?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pa15qsh1xp0w9n8bg', 'Cake Turntable (MS)', 'cake-turntable-ms-2qj7', 'Cake Turntable (MS) (Per Piece)', 1100, 100, true, 'Per Piece', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pa15qsh1xp0w9n8bg', 'cqwdfcs1eselp1e7a');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('pirre831rl', 'pa15qsh1xp0w9n8bg', 'https://images.unsplash.com/photo-1595908129746-57ca1a63dd4d?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pom1ukl6p514b4fh2', '12-inch Bread Knife', '12-inch-bread-knife-f9mx', '12-inch Bread Knife (Per Piece)', 240, 100, true, 'Per Piece', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pom1ukl6p514b4fh2', 'cqwdfcs1eselp1e7a');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('piy5qlucnb', 'pom1ukl6p514b4fh2', 'https://images.unsplash.com/photo-1595908129746-57ca1a63dd4d?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('p1mkrpvldg2k6pu8j', 'Measuring Cup Set', 'measuring-cup-set-dqhe', 'Measuring Cup Set (Per Piece)', 120, 100, true, 'Per Piece', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('p1mkrpvldg2k6pu8j', 'cqwdfcs1eselp1e7a');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('piyf8cj3qg', 'p1mkrpvldg2k6pu8j', 'https://images.unsplash.com/photo-1595908129746-57ca1a63dd4d?w=600&auto=format&fit=crop&q=60', true);
INSERT INTO "Product" (id, name, slug, description, "basePrice", stock, "isActive", weight, "updatedAt") VALUES ('pr3ogbmw0fpwqfkyo', '25-Piece Nozzle Set', '25-piece-nozzle-set-jxee', '25-Piece Nozzle Set (Per Pack)', 650, 100, true, 'Per Pack', NOW());
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ('pr3ogbmw0fpwqfkyo', 'cqwdfcs1eselp1e7a');
INSERT INTO "ProductImage" (id, "productId", url, "isPrimary") VALUES ('piay6orpgj', 'pr3ogbmw0fpwqfkyo', 'https://images.unsplash.com/photo-1595908129746-57ca1a63dd4d?w=600&auto=format&fit=crop&q=60', true);
